AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Red Hat OCP Master deployment'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lab information
        Parameters:
          - OpenShiftVersion
          - ClusterName
          - HostedZoneName
          - NumStudents
          - PullSecretUser
          - PullSecret
          - SSHKey
          - SubManagerUser
          - SubManagerPassword
          - RhcosAmi
      - Label:
          default: Security configuration
        Parameters:
          - RemoteAccessCIDR
      - Label:
          default: Network configuration
        Parameters:
          - AvailabilityZone
          - VPCCIDR
          - PublicSubnetCIDR
      - Label:
          default: Cloud9 information
        Parameters:
          - CreateCloud9Instance
          - Cloud9AutoStopInMin
          - Cloud9InstanceType
          - Cloud9UserPassword
      - Label:
          default: CloudFormation Template Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZone:
        default: Availability Zone
      PublicSubnetCIDR:
        default: Public subnet CIDR
      RemoteAccessCIDR:
        default: Remote access CIDR
      VPCCIDR:
        default: VPC CIDR
      OpenShiftVersion:
        default: OpenShift version
      ClusterName:
        default: Cluster Name prefix
      HostedZoneName:
        default: Hosted DNS zone name
      NumStudents:
        default: Number of students
      PullSecretUser:
        default: OCP Service Account for 3.11 container repo
      PullSecret:
        default: OCP Pull Secret
      SSHKey:
        default: Public ssh Key
      SubManagerUser:
        default: Subscription Manager username
      SubManagerPassword:
        default: Subscription Manager password
      RhcosAmi:
        default: "Red Hat Enterprise Linux CoreOS AMI ID"
      CreateCloud9Instance:
        default: Create Cloud9 instance?
      Cloud9AutoStopInMin:
        default: Cloud9 automatic stop time in minutes
      Cloud9InstanceType:
        default: Cloud9 instance type
      Cloud9UserPassword:
        default: Cloud9 user password
      QSS3BucketName:
        default: CloudFormation templates S3 bucket name
      QSS3KeyPrefix:
        default: CloudFormation templates S3 key prefix
Parameters:
  VPCCIDR:
    Description: The CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/18
    Type: String
  AvailabilityZone:
    Description: The Availability Zone to use for the public subnet in the VPC.
    Default: us-west-2a
    Type: AWS::EC2::AvailabilityZone::Name
  PublicSubnetCIDR:
    Description: The CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/20
    Type: String
  RemoteAccessCIDR:
    Description: The remote CIDR range for allowing SSH into the Cloud9 instance.
      We recommend that you set this value to a trusted IP range.
      For example, you might want to grant specific ranges inside your corporate network SSH access.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
  OpenShiftVersion:
    Description: The version of OpenShift to deploy for the lab.
    AllowedValues:
      - "3.11"
      - "4.2"
      - "4.3"
      - "4.6"
    Default: "4.6"
    Type: String
  ClusterName:
    Description: A short, representative cluster name to use for host names and other identifying names. This
      will be combined with the studentNumber to create the full cluster name
    AllowedPattern: ^([a-z][a-z0-9\-]{0,26})$
    ConstraintDescription: Cluster name must be alphanumeric, start with a letter, and have a maximum of 12
      characters and all lowercase.
    MaxLength: 12
    MinLength: 1
    Type: String
  HostedZoneName:
    Description: The Route53 zone to register the targets with, such as example.com. Omit the trailing period. You must create this Route53 Zone before building this Stack.
    Default: "example.com"
    Type: String
  NumStudents:
    Description: The number of student environments to provision for the lab.
    Default: 1
    Type: Number
  PullSecretUser:
    Description: The username for pull Secret Service Account. NOTE - not needed for 4.X installs.
    Default: ""
    Type: String
  PullSecret:
    Description: The Secret used to pull the OpenShift containers from the secure registry.
    Default: ""
    Type: String
    NoEcho: True
  SSHKey:
    Description: The public key to be added to the CoreOS boxes for ssh access.
    Default: ""
    Type: String
  RhcosAmi:
    Description: (Optional) Current Red Hat Enterprise Linux CoreOS AMI to use for bootstrap. Leave this empty to use this Template's to choose the right AMI
    Type: String
  SubManagerUser:
    Description: The username for RHEL subscription. NOTE - not needed for 4.X installs.
    Default: ""
    Type: String
  SubManagerPassword:
    Description: The password for RHEL subscription. NOTE - not needed for 4.X installs.
    Default: ""
    Type: String
    NoEcho: True
  CreateCloud9Instance:
    Description: AWS Cloud9 is a cloud-based integrated development environment (IDE)
    Default: "no"
    Type: CommaDelimitedList
    AllowedValues: ["yes","no"]
  Cloud9AutoStopInMin:
    Description: The time the Cloud9 instance is automatically stopped after no use.
    Default: 30
    Type: Number
  Cloud9InstanceType:
    Description: Instance size of the Cloud9 instance for the student
    AllowedPattern: ^[a-z][1-9][.][a-z0-9]+$
    MinLength: '5'
    MaxLength: '20'
    Default: "t2.micro"
    Type: String
  Cloud9UserPassword:
    Description: The password used to assign to the Cloud9 user, leave blank to use autogenerated
    Default: ""
    Type: String
    NoEcho: True
  QSS3BucketName:
    Description: S3 bucket name for the CloudFormation templates. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Type: String
  QSS3KeyPrefix:
    Description: S3 folder name for the CloudFormation templates. This string can include
      numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: S3 folder name can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: aws-ocp/
    Type: String

Conditions:
    OCP4:
      !Or [ !Equals [!Ref OpenShiftVersion, '4.2'], !Equals [!Ref OpenShiftVersion, '4.3'], !Equals [!Ref OpenShiftVersion, '4.6']]
    OCP3: !Equals [!Ref OpenShiftVersion, '3.11']
    NoRhcosAmiParameter:
      Fn::Equals:
        - !Ref RhcosAmi
        - ""

Mappings:
  OpenShiftVersion:
    # TODO: Can we make this smarter in the lambda to download the version with less inputs
    "3.11":
      OpenShiftMirrorURL: ""
      OpenShiftVersionNum: "3"
      OpenShiftInstallBinary: ""
      OpenShiftClientBinary: ""
      StudentTemplate: "aws-ocp3-student-env.template.yaml"

    "4.2":
      OpenShiftMirrorURL:  "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/"
      OpenShiftVersionNum: "4.2.12"
      OpenShiftInstallBinary: "openshift-install"
      OpenShiftClientBinary: "openshift-client"
      StudentTemplate: "aws-ocp4-student-env.template.yaml"

    "4.3":
      OpenShiftMirrorURL:  "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/"
      OpenShiftVersionNum: "4.3.17"
      OpenShiftInstallBinary: "openshift-install"
      OpenShiftClientBinary: "openshift-client"
      StudentTemplate: "aws-ocp4-student-env.template.yaml"
    
    "4.6":
      OpenShiftMirrorURL:  "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/"
      OpenShiftVersionNum: "4.6.8"
      OpenShiftInstallBinary: "openshift-install"
      OpenShiftClientBinary: "openshift-client"
      StudentTemplate: "aws-ocp4-student-env.template.yaml"


  #
  # Removing hyphens because Keys need to be alphanumeric in the 2nd level mapping. See RhcosAmiMap
  RegionDehyphen:
    us-east-1:
      Value: useast1
    us-east-2:
      Value: useast2
    us-west-1:
      Value: uswest1
    us-west-2:
      Value: uswest2
    sa-east-1:
      Value: saeast1
    eu-west-3:
      Value: euwest3
    eu-north-1:
      Value: eunorth1
    ca-central1:
      Value: cacentral1
    ap-southeast-2:
      Value: apsoutheast2
    ap-southeast-1:
      Value: apsoutheast1
    ap-south-1:
      Value: apsouth1
    ap-northeast-2:
      Value: apnortheast2
    ap-northeast-1:
      Value: apnortheast1
    me-south-1:
      Value: mesouth1


  RhcosAmiMap:
    # 3.11 - RHEL-7.7_HVM-20190923-x86_64-0-Hourly2-GP2
    # 4.2  - rhcos-42.80.20191002.0-hvm
    # 4.3  - rhcos-43.81.202001142154.0-hvm
    "4.2":
      useast1: ami-01e7fdcb66157b224
      useast2: ami-0bc59aaa7363b805d
      uswest1: ami-0ba912f53c1fdcdf0
      uswest2: ami-08e10b201e19fd5e7
      saeast1: ami-03f6b71e93e630dab
      euwest3: ami-058ad17da14ff4d0d9
      euwest2: ami-00c74e593125e0096
      euwest1: ami-04370efd78434697b
      eunorth1: ami-0175e9c9d258cc11d
      eucentral1: ami-092b69120ecf915ed
      cacentral1: ami-04419691da69850cf
      apsoutheast2: ami-0391e92574fb09e08
      apsoutheast1: ami-0d76ac0ebaac29e404
      apsouth1: ami-0bd772ba746948d9a
      apnortheast2: ami-014514ae47679721b
      apnortheast1: ami-0426ca3481a088c7b

    "4.3":
      useast1: ami-06f85a7940faa3217
      saeast1: ami-0c80d785b30eef121
      useast2: ami-04a79d8d7cfa540cc
      uswest1: ami-0633b392e8eff25e7
      uswest2: ami-0d231993dddc5cd2e
      euwest3: ami-0049e16104f360df6
      mesouth1: ami-0b03ea038629fd02e
      euwest2: ami-0eef98c447b85ffcd
      euwest1: ami-0e95125b57fa63b0d
      eunorth1: ami-06b7087b2768f644a
      eucentral1: ami-0ceea534b63224411
      cacentral1: ami-0f6d943a1fa9172fd
      apsoutheast2: ami-08929f33bfab49b83
      apsoutheast1: ami-086b93722336bd1d9
      apsouth1: ami-0bf62e963a473068e
      apnortheast2: ami-0ba4f9a0358bcb44a
      apnortheast1: ami-023d0452866845125

    "4.6":
      useast1: ami-009cbe327d180d666
      saeast1: ami-081f13881a31af160
      useast2: ami-0346f64579665ce3c
      uswest1: ami-07c185c787029b522
      uswest2: ami-01105d480bb47353f
      euwest3: ami-083f281d2864a71de
      mesouth1: ami-05a6ae5eadb5b244d
      euwest2: ami-0291fd4543d6940f4
      euwest1: ami-0e514a30ad261c978
      eunorth1: ami-06d01bfaf14ad66a3
      eucentral1: ami-0a51f61236e6fc6f2
      cacentral1: ami-0f5825ef10c76de32
      apsoutheast2: ami-0e3e2b2ea00c35823
      apsoutheast1: ami-0a6a0f1f6106708c4
      apsouth1: ami-09253ba33f828d47f
      apnortheast2: ami-01e554d608de6087a
      apnortheast1: ami-0cb46ba6945dbfebe

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-ocp-vpc.template.yaml'
      Parameters:
        AvailabilityZone:
            Ref: AvailabilityZone
        PublicSubnetCIDR:
            Ref: PublicSubnetCIDR
        VPCCIDR:
          Ref: VPCCIDR

  IgnitionBucket:
    Type: AWS::S3::Bucket

  LambdaZipsBucket:
    Type: AWS::S3::Bucket

  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-ocp-iam.template.yaml'
      Parameters:
        LambdaZipsBucketName: !Ref LambdaZipsBucket
        IgnitionBucketName: !Ref IgnitionBucket
        ClusterName: !Ref ClusterName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-ocp-lambda.template.yaml'
      Parameters:
        LambdaZipsBucketName: !Ref LambdaZipsBucket
        CopyZipsRoleArn: !GetAtt IamStack.Outputs.CopyZipsRoleArn
        StackDirectorRoleArn: !GetAtt IamStack.Outputs.StackDirectorRoleArn
        AuthBucket: !Ref IgnitionBucket
        ClusterName: !Ref ClusterName
        NumStudents: !Ref NumStudents
        HostedZoneName: !Ref HostedZoneName
        OpenShiftMirrorURL: !FindInMap
          - OpenShiftVersion
          - !Ref OpenShiftVersion
          -  OpenShiftMirrorURL
        OpenShiftVersion: !FindInMap
          - OpenShiftVersion
          - !Ref OpenShiftVersion
          -  OpenShiftVersionNum
        OpenShiftClientBinary: !FindInMap
          - OpenShiftVersion
          - !Ref OpenShiftVersion
          - OpenShiftClientBinary
        OpenShiftInstallBinary: !FindInMap
          - OpenShiftVersion
          - !Ref OpenShiftVersion
          -  OpenShiftInstallBinary
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        CreateCloud9Instance: !Join ["", !Ref CreateCloud9Instance]
        PullSecret: !Ref PullSecret
        SSHKey: !Ref SSHKey

  StudentStacksOCP4:
    Condition: OCP4
    Type: Custom::LambdaDeployCF
    Properties:
      Function: DeployCF
      ServiceToken: !GetAtt LambdaStack.Outputs.StackDirectorLambdaArn
      StackName: !Ref ClusterName
      TemplateURL:
        Fn::Sub:
          - "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/${CurStudentTemplate}"
          - CurStudentTemplate: !FindInMap [OpenShiftVersion, !Ref OpenShiftVersion, StudentTemplate]
      VpcId: !GetAtt 'VPCStack.Outputs.VPCID'
      SubnetId: !GetAtt 'VPCStack.Outputs.PublicSubnetID'
      VPCCIDR: !Ref VPCCIDR
      RemoteAccessCIDR: !Ref RemoteAccessCIDR
      MasterStack: !Sub ${AWS::StackName}
      OpenShiftVersion: !Ref OpenShiftVersion
      NumStacks: !Ref NumStudents
      HostedZoneName: !Ref HostedZoneName
      RhcosAmi: !If
        - NoRhcosAmiParameter
        - !FindInMap
          - RhcosAmiMap
          - !Ref OpenShiftVersion
          - !FindInMap
            - RegionDehyphen
            - !Ref AWS::Region
            - Value
        - !Ref RhcosAmi
      IgnitionLocation: !If [OCP4, !Sub "s3://${IgnitionBucket}", "" ]
      CreateCloud9Instance: !Join ["", !Ref CreateCloud9Instance]
      Cloud9AutoStopInMin: !Ref Cloud9AutoStopInMin
      Cloud9InstanceType: !Ref Cloud9InstanceType
      Cloud9UserPassword: !Ref Cloud9UserPassword
      QSS3BucketName: !Ref QSS3BucketName
      QSS3KeyPrefix: !Ref QSS3KeyPrefix

  StudentStacksOCP3:
    Condition: OCP3
    Type: Custom::LambdaDeployCF
    Properties:
      ServiceToken: !GetAtt LambdaStack.Outputs.StackDirectorLambdaArn
      StackName: !Ref ClusterName
      TemplateURL:
        Fn::Sub:
          - "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/${CurStudentTemplate}"
          - CurStudentTemplate: !FindInMap [OpenShiftVersion, !Ref OpenShiftVersion, StudentTemplate]
      VpcId: !GetAtt 'VPCStack.Outputs.VPCID'
      SubnetId: !GetAtt 'VPCStack.Outputs.PublicSubnetID'
      RemoteAccessCIDR: !Ref RemoteAccessCIDR
      NumStacks: !Ref NumStudents
      HostedZoneName: !Ref HostedZoneName
      PullSecretUser: !Ref PullSecretUser
      PullSecret: !Ref PullSecret
      SSHKey: !Ref SSHKey
      IgnitionBucketName: !Ref IgnitionBucket
      SubManagerUser: !Ref SubManagerUser
      SubManagerPassword: !Ref SubManagerPassword
      CreateCloud9Instance: !Join ["", !Ref CreateCloud9Instance]
      Cloud9AutoStopInMin: !Ref Cloud9AutoStopInMin
      Cloud9InstanceType: !Ref Cloud9InstanceType
      Cloud9UserPassword: !Ref Cloud9UserPassword
      QSS3BucketName: !Ref QSS3BucketName
      QSS3KeyPrefix: !Ref QSS3KeyPrefix


  ValidateEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ClusterName}-ValidateEvent
      ScheduleExpression:  "rate(1 hour)"
      Targets:
        - Arn: !GetAtt LambdaStack.Outputs.StackDirectorLambdaArn
          Id: !Sub ${ClusterName}-ValidateDeploymentLambda

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaStack.Outputs.StackDirectorLambdaArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - "ValidateEvent"
          - "Arn"

Outputs:
  WorkshopWebpage:
    Value: !Sub 'https://${IgnitionBucket}.s3.amazonaws.com/workshop.html'
